# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: 'E2E Reports'
on:
  workflow_run:
    workflows: [ 'E2E Tests' ]
    types:
      - completed

env:
  JIRA_ACCESS_TOKEN: ${{ secrets.JIRA_ACCESS_TOKEN }}
  ADMIN_APP_VERSION: '2.4.0'
  PROJECT_ID: '11900'
  CYCLE_NAME: 'Automation Cycle'
  TASK_NAME: 'Playwright Automation Task'
  FOLDER_NAME: 'Playwright Automation Run'
  RESULTS_FILE: 'playwright-results'

jobs:
  report:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
    - name: Generate report
      uses: dorny/test-reporter@0d00bb14cb0cc2c9b8985df6e81dd333188224e1 #v1.5.0
      with:
        artifact: ${{ env.RESULTS_FILE }}
        name: Playwright Tests
        path: '*.xml'
        reporter: java-junit
    - name: Extract Artifact
      run: Expand-Archive "${{ env.RESULTS_FILE }}.zip"
      shell: pwsh
    - name: Send report to Zephyr
      if: contains(github.ref, 'main')
      run: |
        Write-Host "Sending test results for branch ${{github.ref}}"
        $parameters = @{
            cycleName = '${{ env.CYCLE_NAME }}'
            taskName = '${{ env.TASK_NAME }}'
            folderName = '${{ env.FOLDER_NAME }}'
        }
        .\eng\send-test-results.ps1 -PersonalAccessToken ${{ env.JIRA_ACCESS_TOKEN }} -ProjectId ${{ env.PROJECT_ID }} -AdminAppVersion '${{ env.ADMIN_APP_VERSION }}' -ResultsFilePath '${{ env.RESULTS_FILE }}/${{ env.RESULTS_FILE }}.xml' -ConfigParams $parameters
      shell: pwsh
